### ISSUE TITLE
makeCellStyle  cannot be applied to the table, only table header

### ISSUE THREAD

**Issue by melDavila** [mbleron/ExcelGen#10]
In table content format, sometime I need to align left or right.
Or some columns must be RED.

The use of makeCellStyle can only affect the header.

**Comment by melDavila** [comment]
For example:
add a parameter to **setColumnFormat**
procedure setColumnFormat (
  p_ctxId     in ctxHandle
, p_sheetId   in sheetHandle
, p_columnId  in pls_integer
, p_format    in varchar2
**,p_style  in cellStyleHandle**
);

**Comment by mbleron** [comment]
See:
* [setRowProperties](https://github.com/mbleron/ExcelGen#setrowproperties-procedure)
* [setTableRowProperties](https://github.com/mbleron/ExcelGen#settablerowproperties-procedure)
* [setColumnProperties](https://github.com/mbleron/ExcelGen#setcolumnproperties-procedure)
* [setTableColumnProperties](https://github.com/mbleron/ExcelGen#settablecolumnproperties-procedure)
