### ISSUE TITLE
xutl_xlsb fails compile

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#16]
Package body xutl_xlsb obtained via:

    git clone --recurse-submodules https://github.com/mbleron/ExcelGen.git

fails to compile. Error at line 1894 trying to read table *xlsb_record_types*.

I commented out the procedure *read_all* in the package spec and body in order to continue. It is not functionality I'm using.

**Comment by mbleron** [comment]
My bad.
It's some personal debug stuff I forgot to remove before committing.
I'll fix that ASAP.

**Comment by mbleron** [comment]
Submodule updated.
