### ISSUE TITLE
Apply a style to a column

### ISSUE THREAD

**Issue by adrianboangiu** [mbleron/ExcelGen#19]
Hello,
Congrats for this very useful project.
I search the possibility to apply color to a column? I couldn’t find it.
Is it possible or will it be possible to do it in the future?
Thank you

**Comment by mbleron** [comment]
Hi Adrian,
Issue #10 already covers this requirement.
I'm currently working on it, and should be available within the next couple of weeks.

**Comment by mbleron** [comment]
See:
* [setRowProperties](https://github.com/mbleron/ExcelGen#setrowproperties-procedure)
* [setTableRowProperties](https://github.com/mbleron/ExcelGen#settablerowproperties-procedure)
* [setColumnProperties](https://github.com/mbleron/ExcelGen#setcolumnproperties-procedure)
* [setTableColumnProperties](https://github.com/mbleron/ExcelGen#settablecolumnproperties-procedure)
