### ISSUE TITLE
Cannot install ExcelGen and ExcelTable in the same user

### ISSUE THREAD

**Issue by adrianboangiu** [mbleron/ExcelGen#22]
Hello,

I want to use both tools from the same Oracle user but I cannot install with the actual scripts. I get the following error 
Error report -
ORA-02303: cannot drop or replace a type with type or table dependents
02303. 00000 -  "cannot drop or replace a type with type or table dependents"
when running the second tool install script for 
create or replace type ExcelTableCell

I try to modify the install scripts but the components ExcelCommons and MSUtilities are at different version level and therefore I don't know which version shall I take. I think that both tools should share the same ExcelCommons and MSUtilities components.

Best regards

**Comment by mbleron** [comment]
I've updated submodules in both ExcelGen and ExcelTable to their latest commits.
ExcelTableCell creation script now handles existing dependencies and doesn't error out. That was actually suggested earlier by @lee-lindley via a PR that I merged today as well.
