### ISSUE TITLE
ExcelGen v3

### ISSUE THREAD

**Issue by adrianboangiu** [mbleron/ExcelGen#28]
Hello,

Do you have a forecast for the release date of v3? There are some interesting features announced in this version.

Thank you
Adrian Boangiu

**Comment by mbleron** [comment]
Hi Adrian,
Thanks for your interest.
I'm still in the dev phase. Initially planned to finish during my summer holidays but they're over now and only have weekends left to fully focus on it.
I hope I get it done by the end of the month.
