### ISSUE TITLE
setColumnFormat and setColumnProperties step on each other

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#29]
I suspect this will be swept up in your redesign, but this is what I've observed.

If I call setColumnFormat to set the Excel format string for the number, then I call setColumnProperties to apply a style (font is my goal), then I get the font but not the number format.
If I call setColumnProperties first, then setColumnFormat, I get the number format, but not the style (font).

I looked through documentation and didn't see any way around this. I did not look at the code.  Knowing that you are in the middle of reworking all this I didn't go any further.

**Comment by mbleron** [comment]
The obvious way around this is to apply both via the same `setColumnProperties` call.

Thanks for mentioning this issue anyway. Indeed, we probably don't want to override the whole style if we just need to set a particular property.
It is something I've been thinking about recently, but for a different scenario : merging row-level and column-level styles.

**Comment by mbleron** [comment]
As of v3, `setColumnFormat` will merge the number/date format with the style already defined on the target column (if any), instead of overwriting it entirely.
