### ISSUE TITLE
Can ExcelGen assigns cell with formula within?

### ISSUE THREAD

**Issue by shenyenwu** [mbleron/ExcelGen#30]
Hi mbleron:
	First of all, thank you for the great work, ExcelGen really helps a lot ! 
        I am wondering if ExcelGen has a way to fill formula into specific cell? (Sorry I can not find it in user guild).
	For example: Excel colunn A1 ~ A10 contains user training hours. Assign B1 formula with =sum(A:A) for user dynamically summarize the data.
Thank you for your help.

**Comment by mbleron** [comment]
Hi,
Thanks for your support.
I'm planning to add formulas in a future release.

**Comment by shenyenwu** [comment]
Really ?! Thank you for your help.

**Comment by mbleron** [comment]
Done in V4.0.
See [README](https://github.com/mbleron/ExcelGen/blob/master/README.md#formula-support) for more info.
