### ISSUE TITLE
backwards compatibility and regression

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#31]
Marc,
First, version 3 has so many features that I want, it makes me excited to get it into environments I support so that I can take advantage of it. Outstanding work!

I was hoping to install Version 3 with a package name such as ExcelGen_v3 to avoid regression test of multiple production objects that use Version 2. The SDLC rules and processes under which many of us operate make that regression testing expensive.

Unfortunately, there are enough changes in ExcelCommons, especially xutl_xlsb, that I don't think that will fly. Even if the latest version of ExcelCommons is backwards compatible with ExcelGen v2 (I suspect it is), the rules under which we operate mandate regression testing. I need to version all of the changed objects in ExcelCommons and the calls to those in ExcelGen_v3 in order to avoid that regression test expense.

I'm willing to put some work into it, but the way I have done this in the past with version DEFINE constants as part of the object names is ugly and distracting in the editor.  Another choice is to actually version the object names in the source. Not crazy about that either.

If I'm going to do it for myself only, I'll likley create a Perl script to transform all impacted names (less than a dozen I think) in a copy of the source for deployment. Brutish, but usually effective beyond the occasional need for a manual tweak.

Is this something you would like to see addressed, or is it beyond the scope of what you would like to support? If the former, I'm willing to put in some elbow grease with a little direction. Please advise.

**Comment by mbleron** [comment]
Hi Lee,
Thanks for your feedback.

Indeed, I designed v3 with backward compatibility in mind but we might not be 100% safe from some minor discrepancies.
However, versioning modified objects and all their references seems a bit crazy to me, if you allow me the term.
Are you planning to do this for every new release?

**Comment by lee-lindley** [comment]
Any that I install in a production environment where I cannot justify regression test of everything, yes, I'll version the objects.
If I change a package that is used by multiple jobs, all of them require formal regression testing  according to the rules I live by at 3 of my last 4 engagements. The alternative is not installing a new release.  A new release would need to be compelling to make replacement happen. Maybe version 3 is compelling enough to justify it. Eventually. Not today.

I don't think my situation is an anomaly. I play on big Oracle databases at large corporations who are regulated for the most part (Financial services, an energy utility). This is standard Change Control policy in the United States in those industries (and I assumed international corporations, but maybe not).

Some clients are more rigorous about following the SDLC rules. Others are willing to accept some risk on the word of a developer that it won't break anything. The SDLC policy, however, is clear.  When corporate policy is clearly stated, I see no reason to risk my reputation and livelihood to help them avoid the consequences of their folly.  I find a way to comply. Versioning objects is one way I can comply while still getting what I want.

**Comment by mbleron** [comment]
> I don't think my situation is an anomaly  

I didn't mean it was, sorry if it sounded like that. 
Of course, I'm familiar with SDLC but probably not accustomed to strict applications. 
I'm developing ExcelGen on my free time, independently of my daily job, but at my current shop, people who manage the SDLC are either very eager to push new things in production (under Business pressure mostly), or reluctant to do anything at all, which sometimes results in obsolete apps that prove costly to upgrade or replace ultimately. 

To answer your original question:
> Is this something you would like to see addressed, or is it beyond the scope of what you would like to support?

I'll continue to support a single version through this repo.
Right now, I don't see any fancy way to achieve both maintenability and versioning at the same time, so I guess a batch rename utility is the best way to go.

Or do you have the possibility to create a new dedicated schema to hold v3 objects? This is an approach I've encountered  too, for app upgrade. Then it would just be of matter of granting rights and creating synonyms (if needed).

**Comment by lee-lindley** [comment]
The following perl script seems to work. Not sure if it is worth sharing as unsupported example. I think you can close the issue. 

#!/usr/bin/env perl
use strict;
use warnings;
#
# In each git module and submodule, did "git diff --name-only prior_version_tag_or_commit"
# That gives us list of objects we need to version and install that are different than
# what we already deployed.
# Then you need to go look at dependencies to see if any are used by objects not changed :(
# ExcelTableCell is really the only one I was concerned with. It is used by ExcelTableCellList
# which must be added to the list
my @words_to_version = qw/excelgen exceltablecell exceltablecelllist exceltypes xutl_xlsb/;

for my $f (qw!
plsql/ExcelGen.pkb
plsql/ExcelGen.pks
ExcelCommons/plsql/ExcelTableCell.tps
ExcelCommons/plsql/ExcelTableCellList.tps
ExcelCommons/plsql/ExcelTypes.pkb
ExcelCommons/plsql/ExcelTypes.pks
ExcelCommons/plsql/xutl_xlsb.pkb
ExcelCommons/plsql/xutl_xlsb.pks
!) {
    my $ofname;
    ($ofname = $f) =~ s/\.(.*)/_v3.$1/; # new output file name has version string before dot
    open F, '<', $f;
    open OF, '>', $ofname;
    print STDERR "Creating $ofname\n";
    while (<F>) {
        for my $w (@words_to_version) {
            # the character set [a-z0-9_#$] is valid plsql identifier characters
            # Probably could have avoided the lookahead and lookbehind, but I started down that road.
            s/(^|(?<=[^a-z0-9_#\$]))($w)($|(?=[^a-z0-9#_\$]))/${2}_v3/ig;
        }
        print OF;
    }
    close OF;
    close F;
}

**Comment by lee-lindley** [comment]
Sorry, should have looked at preview. It turned my comments into headings :(

**Comment by lee-lindley** [comment]
This seems to work. The entire thread might be better suited to a wiki than an issue. I think you can close it.
```perl
#!/usr/bin/env perl
use strict;
use warnings;
#
# In each git module and submodule, did "git diff --name-only prior_version_tag_or_commit"
# That gives us list of objects we need to version and install that are different than
# what we already deployed.
# Then you need to go look at dependencies to see if any are used by objects not changed :(
# ExcelTableCell is really the only one I was concerned with. It is used by ExcelTableCellList
# which must be added to the list
my @words_to_version = qw/excelgen exceltablecell exceltablecelllist exceltypes xutl_xlsb/;

for my $f (qw!
plsql/ExcelGen.pkb
plsql/ExcelGen.pks
ExcelCommons/plsql/ExcelTableCell.tps
ExcelCommons/plsql/ExcelTableCellList.tps
ExcelCommons/plsql/ExcelTypes.pkb
ExcelCommons/plsql/ExcelTypes.pks
ExcelCommons/plsql/xutl_xlsb.pkb
ExcelCommons/plsql/xutl_xlsb.pks
!) {
    my $ofname;
    ($ofname = $f) =~ s/\.(.*)/_v3.$1/; # new output file name has version string before dot
    open F, '<', $f;
    open OF, '>', $ofname;
    print STDERR "Creating $ofname\n";
    while (<F>) {
        for my $w (@words_to_version) {
            # the character set [a-z0-9_#$] is valid plsql identifier characters
            # Probably could have avoided the lookahead and lookbehind, but I started down that road.
            s/(^|(?<=[^a-z0-9_#\$]))($w)($|(?=[^a-z0-9#_\$]))/${2}_v3/ig;
        }
        print OF;
    }
    close OF;
    close F;
}
```
