### ISSUE TITLE
Default font for sheet

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#32]
We have cellStyleHandle assignment at the cell, column, row and header level.
We have Number, Date and DateTime formatting that can be applied at the sheet or workbook level.
My request is for a sheet (and/or workbook) level default cell style. Specifically our business partners want their giant spreadsheets to use Arial 8 point font.
Just like with column properties, I can see the header cells not necessarily using this default. That seems appropriate since the header will almost always need a modified style anyway.
The method we must use today is to set it in the header, but then also set the style for every column. That isn't terribly onerous, but it is easy to change the number of columns in the query and forget to update the loop limit for the style assignment.

Since the workaround isn't that hard, I don't think it is a very high priority. I might be able to figure out how to provide a pull request for this, but I know you did a lot of work in style management, including CSS, so it may be biting off more than I can chew.

**Comment by mbleron** [comment]
That's doable.
My only concern is that it may generate a lot of style merging operations to propagate the default style to lower levels, for individual cells at least.

**Comment by lee-lindley** [comment]
I believe you understand my use case which is not concerned with individual cells addressed individually, just "table" level from a query. If it simplifies things, this could be a style applied at the same level as setTableColumnProperties and setTableRowProperties.
A global style for the sheet or workbook would be gravy. I'm just trying to get away from doing it for every column in a query.

**Comment by lee-lindley** [comment]
I'm addressing this with a utility that calls setTableColumnProperties with a style defining the font for all columns in the query. It has to know how many columns are in the query, but it works. This conveniently uses the coordinate system of the query data. Outside of the utility my program that is aware of which columns in the query require an accounting number format is calling setColumnFormat. That is using the sheet coordinate system. :(

A setTableColumnFormat procedure would be nice; however, you may be able to clarify something about merging styles. I know you allow the number/date formats to be merged when set in sequential calls with other cell/column properties. If there are multiple calls to setTableColumnProperties are the style elements merged if the new one does not have a value for what is already present? In other words, could I create a cell style that has only the number format set and call setTableColumnProperties again without overriding the font previously assigned? If so, it would be worth mentioning in the documentation. My alternative is to fully define the style including the accounting format and font and override the one set by the utility.

**Comment by mbleron** [comment]
> If there are multiple calls to setTableColumnProperties are the style elements merged if the new one does not have a value for what is already present?

Not in this case. The new style replaces the previous one altogether.

**Comment by mbleron** [comment]
Added in v3.1:
- [setTableColumnFormat](https://github.com/mbleron/ExcelGen#settablecolumnformat-procedure)
- [setDefaultStyle](https://github.com/mbleron/ExcelGen#setdefaultstyle-procedure)
- [setRangeStyle](https://github.com/mbleron/ExcelGen#setrangestyle-procedure)
