### ISSUE TITLE
documentation - putCell

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#33]
README.md entries for putDateCell, putNumberCell and putStringCell have "putCell" as the procedure name. Perhaps you initially planned to make it overloaded.

**Comment by lee-lindley** [comment]
Function makeCellRef parameter names lack the "p_" prefix shown in README.md.

**Comment by mbleron** [comment]
Good catch on `makeCellRef`. Used to be a private function.
I'm gonna commit this change right now because it has some impact on function usage.
