### ISSUE TITLE
Latest ExcelGen master branch(86c1524) wrong arguments at line 2517

### ISSUE THREAD

**Issue by fddc** [mbleron/ExcelGen#36]
xutl_xlsb.put_BeginWsView(stream);

**Comment by mbleron** [comment]
There's no such code at line 2517 in the latest version (v3.0.1).
There is in v2.5.1 though : 
https://github.com/mbleron/ExcelGen/blob/fd9e5cd81c42c8501d876e354cb36c03986b3c88/plsql/ExcelGen.pkb#L2517
So installation issue most likely. Use all components from the latest commit.

**Comment by fddc** [comment]
I mixed up the component  version
Thank you.
