### ISSUE TITLE
bug: multiple tables on 1 sheet cannot use setTableColumnProperties

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#37]
I had hoped to use one table for multi-row column headers, then the main table below them using relative positioning. It works but using setTableColumnProperties on both tables in the sheet does not work as expected. In my real code the resulting spreadsheet causes excel to crash with no information (which could be something else, but this is the first thing I could prove). In the attached example it sets the font on the first table but not the background color. On the second table it does not set the font. 
I'm guessing both of these calls are really doing a sheet level property call and are stepping on each other?
[multi-table-col-properties-bug.zip](https://github.com/mbleron/ExcelGen/files/10059607/multi-table-col-properties-bug.zip)

**Comment by lee-lindley** [comment]
This is not the problem, sorry. I have a mistake in the test case.

**Comment by lee-lindley** [comment]
There is no bug. There is a case you can trap for that might prevent some future sap from beating their head against the wall trying to figure out their problem.

  table1 := ExcelGen.addTable(ctx, sheet1, q'{SELECT 'top', 'top', 'top' FROM dual UNION ALL SELECT 'mid','mid', 'mid' FROM dual}'
        ,p_anchorColOffset => NULL
        **,p_anchorRowOffset => 0**
  );

Zero is bad. Zero causes the resulting .xlsx file to crash excel. Why did I use 0? Because my parameter is an "adder" parameter. Long story.
It would be nice if anywhere a positioning argument of zero causes bad things to happen, that ExcelGen rejects it and blows up on that call with an appropriate Raise Error. 

Please close the issue. If you like I can enter a new one for the real problem.

**Comment by mbleron** [comment]
That sounds familiar. 
I encountered a similar problem while coding `master-details.sql`:
https://github.com/mbleron/ExcelGen/blob/86c15245f03cff386ea27d9d60e615aa8ff890f9/test_cases/master-details.sql#L13-L17
Because the first table needs absolute positioning, I couldn't use the same logic as for the others which use relative positioning.

I'll add a few sanity checks as you suggest.
(Leaving this one open as a reminder)

**Comment by mbleron** [comment]
Done in v3.1.
