### ISSUE TITLE
question: possibility to force data type ?

### ISSUE THREAD

**Issue by Michel-Gzt** [mbleron/ExcelGen#38]
Hello mbleron,

Many thanks for your great work, excelGen saved (and still saves) us a lot of time !

Here's what I could need your help on :
My use case is calling addSheetFromQuery with a SQL request I can’t modify, which returns text, dates & number, all in text format.
I’d like to know if there is a way to force a type to be applied on columns, even if not present in the source SQL.

e.g. I'd like to be able to call : 
sql_request := 'select ''test'', to_char(sysdate) from dual';
sheet1 := ExcelGen.addSheetFromQuery(ctxId, sheetName, sql_request);

and still have a way to force sysdate to be recognized as a date in generated xls file, without modifying sql_request

Thanks !

**Comment by mbleron** [comment]
Hi Michel,

I understand what you're asking but I'm afraid that is beyond the scope of ExcelGen right now.

If you know which columns need to be re-cast, you may build a new query on top of the original one with the necessary transformations in the SELECT.
I can provide some sample code for that if you like.

Marc.

**Comment by Michel-Gzt** [comment]
hello,

Thanks for the quick answer :)
This is exactly what I was trying to avoid, our request generation is a bit complex - but if there's no choice, well...

And thanks again for the help proposition, but I'll be able to manage this on my side.

Michel
