### ISSUE TITLE
styles on null cells

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#39]
When a cell has no value (NULL in a query result), a style applied to the row or column via _set_table_column_properites_ or _set_table_row_properties_ does not apply to the empty cell. This is most apparent when a background color is part of the style.
I note this with an example in [Creating Multiple Row Headers with ExcelGen PL/SQL Spreadsheet Generator](https://lee-lindley.github.io/oracle/plsql/2022/11/27/ExcelGen_multirow_headers.html) near the top of the blog post beneath the screenshot.
I suspect you are addressing an issue with setting the style at the sheet level which causes it to extend the style past the end of the data, but the current behavior seems suboptimal.

I would prefer that the *set_table_[row,column]_properties* methods recognize the boundaries of the query result  set and set the property on all cells in the orthogonal region populated as a "table", whether an individual cell is populated or not.

A similar problem could happen with _put_cell_, so a method or parameter option to put a null value such that the background style is applied would be useful. I may be wrong on this one as my own code may have skipped null cells. :)

I could also be wrong on the situation with _set_row_properties_ and _set_column_properties_. I'm asserting that they set the style for the entire sheet, spreading a background color past the extent of any data. That is my recollection, but I didn't build a test today to prove it.

**Comment by mbleron** [comment]
This happens when the NULL is of string data type (CHAR or VARCHAR2).
It is a side-effect of not generating any cell for NULL string values, which was done on purpose prior v3 to save some space, but not relevant anymore with the introduction of styling everywhere.
The same goes for `putStringCell`.
I'll fix that in the upcoming version.

**Comment by mbleron** [comment]
Fixed in v3.1.
