### ISSUE TITLE
bug - setTableColumnProperties p_columnName parameter

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#40]
[bug_column_format.zip](https://github.com/mbleron/ExcelGen/files/10420582/bug_column_format.zip)
Attached files demonstrate a bug that manifests under some conditions when overriding the column header name using _setTableColumnProperties_. **The bug is that not all columns from the query are written to the spreadsheet**. Observation from the original program is that the data type (date) may not have been correct on one of the last columns present when there is data. Not sure that hint is helpful.

The table in the zip file needs to be present for 2 of the 3 results in this demonstrattion. No data is needed. No data rows are involved in the demonstration, but it also happens with real data in the program where we found the problem.

Two of the cases show that the bug does NOT manifest unless both factors are present. I've narrowed it down as much as I can for now. To go further I would need to add debug statements in ExcelGen and I'm not yet up to speed on version 3.01 code and model.

If I can do anything that will help you with the test case, please let me know. Thanks Marc.

**Comment by mbleron** [comment]
The `v_columnHeaderRow` collection has 47 names, while the table has only 41 columns, that's why we only get that much in the resulting file.
Or Am I missing something?

**Comment by lee-lindley** [comment]
Nope. I'm working with a junior developer and never conceived of the possibility that he removed columns from the query, and when we encountered the problem, he never thought of it either. I was tryiing to do this intermittently while with family and obviously did not focus well enough.
This is the second time I've given you a bogus problem and my face is red.
Please close the issue.
