### ISSUE TITLE
Enhancement - return rowcounts after getFileConent

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#44]
I have a prototype for maintaining rowcount sum after each fetch in a member attribute of sql_metadata_t. Then for any given sheet/table combination, the below function will return the rowcount (but only after calling getFileContent/createFile and before closeContext). I can create a pull request if you are willing.
It is enough of a kludge that I can be talked out of it; however, I'm on my third client where eveybody wants the rowcount(s), even if it is after the spreadsheet is created. If you have a better suggestion for how to structure it, I'm willing to do the work. If you don't want to include it, I'm OK with that too.
```
 function getRowCount(
    p_ctxId       in ctxHandle
  , p_sheetIdx    in sheetHandle 
  , p_tableIdx    in tableHandle
  ) return pls_integer
  is
  begin
    loadContext(p_ctxId);
    return currentCtx.sheetDefinitionMap(p_sheetIdx).tableList(p_tableIdx).sqlMetadata.rowcount;
  end getRowCount;
```

**Comment by lee-lindley** [comment]
I see the member `r_num` already collects the rowcount. So the change would be only to provide a public function to access it. What I propose above should work just replacing rowcount with r_num.

**Comment by lee-lindley** [comment]
```
 function getRowCount(
    p_ctxId       in ctxHandle
  , p_sheetIdx    in sheetHandle 
  , p_tableIdx    in tableHandle default 1
  ) return pls_integer
  is
  begin
    loadContext(p_ctxId);
    return currentCtx.sheetDefinitionMap(p_sheetIdx).tableList(p_tableIdx).sqlMetadata.r_num;
  end getRowCount;
```
Only it doesn't work -- the value of r_num is NULL even after calling createFile. I'm not 100% sure, but it looks like we are updating a copy of the record `sqlMetadata` and it never is put back into the structure. I'm not confident about that because there are other fields in that record you are updating in this procedure. I'll do more debugging this weekend. We should be able to make this work.

**Comment by mbleron** [comment]
Yes, `sd` is a local copy of the sheet definition in `createWorksheet` procedure, which is passed around to the generation routines.
We just have to store it back in the context at the end.

I'll add the new function as part the next version, along with fixes for #42 and #43, and credit you as co-author.

**Comment by lee-lindley** [comment]
Cool. Added assignment of `sd` back to `sheetDefinitionMap` at the bottom of `createWorksheet` and now it works.
Don't worry about the credit.
Would be nice to also add  sheetIdx, tableIdx and r_num to the debug calls currently printing 'end fetch':

`debug('end fetch sheetIdx='||TO_CHAR(sd.sheetIndex)||' tableIdx='||TO_CHAR(tId)||' rowcount='||TO_CHAR(t.sqlMetadata.r_num) );`

Thanks Marc

**Comment by lee-lindley** [comment]
Confirmed working as designed. Thanks Marc.
