### ISSUE TITLE
individual column header cell properties

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#45]
Use Case: Make the background lightgray for most column headers, but lightskyblue and purple for specific columns.

We can create headers independent of the table data and have complete control over everything except AutoFilter. This is one workaround and the user can set autofilter manually if they need it, so priority for this seems fairly low.

If we want to set AutoFilter on, we must use setHeader or setTableHeader. This does not give us ability to change the format on individual column header cells.
I attempted setRangeStyle without success. I suspect the setHeader properties come last and overwrite those.

**Comment by mbleron** [comment]
We could add another optional parameter in `setTableColumnProperties` to override the header style : 
```
procedure setTableColumnProperties (
  p_ctxId       in ctxHandle
, p_sheetId     in sheetHandle
, p_tableId     in pls_integer
, p_columnId    in pls_integer
, p_columnName  in varchar2 default null
, p_style       in cellStyleHandle default null
, p_headerStyle in cellStyleHandle default null
);
```

**Comment by lee-lindley** [comment]
That works well and addresses something I noted about this method being a little weird in addressing column header properties on the one hand and column data properties on the other. This adds clarity that it addresses both. I like it.

As for implementation, I'm not there yet on understanding the style model and when you apply what.  I can see storing the column header xfId overide in a new attribute in table_column_t that would take precedence over the value in t.rowMap(0).xfId, but where it is written in createWorksheet* has some logic with mergeCellStyle that gives me pause. I am willing to make an attempt at it, but I fear it would cost you more time to vet my work than to do it yourself. If you want to leave this asside for awhile, I'll take a stab at it. You may not want the bother though, and I'm fine with that too.

**Comment by mbleron** [comment]
I'll do the implementation today, shouldn't take me long.

**Comment by mbleron** [comment]
Done in v3.2.

```
declare

  ctx     ExcelGen.ctxHandle;
  sheet1  ExcelGen.sheetHandle;
  table1  ExcelGen.tableHandle;

begin

  ctx := ExcelGen.createContext(ExcelGen.FILE_XLSX);
  sheet1 := ExcelGen.addSheet(ctx, 'sheet1');

  table1 := ExcelGen.addTable(ctx, sheet1, 'select employee_id, first_name, last_name, salary from hr.employees where department_id = 50');
  ExcelGen.setTableHeader(ctx, sheet1, table1, ExcelGen.makeCellStyleCss(ctx, 'background:lightgray'), true);
  ExcelGen.setTableColumnProperties(ctx, sheet1, table1, 1, p_headerStyle => ExcelGen.makeCellStyleCss(ctx, 'background:lightskyblue'));
  ExcelGen.setTableColumnProperties(ctx, sheet1, table1, 4, p_headerStyle => ExcelGen.makeCellStyleCss(ctx, 'background:purple'));
  --ExcelGen.setColumnProperties(ctx, sheet1, 4, ExcelGen.makeCellStyleCss(ctx, 'color:red'));
  ExcelGen.createFile(ctx, 'TEST_DIR', 'header-style.xlsx');
  ExcelGen.closeContext(ctx);

end;
/
```

**Comment by lee-lindley** [comment]
Works like a champ, but I don't know what they were thinking when they told me a purple background. That has to go :)
Thanks Marc!

**Comment by mbleron** [comment]
Depending on the perceived brightness (or luminance) of the background, we may want to switch to a black or white text color to achieve better contrast.
I had to deal with this situation a while ago when the end user would choose an arbitrary background color but didn't want to bother about the foreground color.
There are various formulas available, e.g. 
https://stackoverflow.com/questions/596216/formula-to-determine-perceived-brightness-of-rgb-color
