### ISSUE TITLE
Maximum amount of rows to be fetched as a parameter?

### ISSUE THREAD

**Issue by v-hlotau** [mbleron/ExcelGen#50]
Could the procedures/functions **addSheetFromQuery**, **addSheetFromCursor**, **addTable** be extended to include an additional parameter to limit the maximum amount of rows to be fetched?
Something like the parameter **p_max_rows** in the APEX procedure **APEX_EXEC.OPEN_QUERY_CONTEXT**.
Or could I use the parameter **p_pageSize** for that purpose?
Maybe its the wrong place to do this limitation anyway and I should limit the rows in the query?

**Comment by mbleron** [comment]
For now, the parameter `p_pageSize` can only be used in conjunction with `p_paginate` but it's a good candidate for your use case.
I'll look into this tomorrow, should be an easy one.

**Comment by lee-lindley** [comment]
On an application I support, I appended "Fetch next 100000 rows only" to the end of query strings. It was a procedure call that did this. Doesn't work for passing in an open cursor, but is just dandy for passing in a query strings. It also had an option for recognizing the limit was reached, but that's another story.
HTH

**Comment by mbleron** [comment]
On second thought, we may want to limit the number of rows fetched from the query while still be able to paginate across multiple sheets, using a specific page size. In that case, `p_pageSize` cannot be used.
We'll need an additional parameter.

**Comment by mbleron** [comment]
Done in v3.6, along with a few other things.

**Comment by v-hlotau** [comment]
> Done in v3.6, along with a few other things.

Nice work, as always. Thank you!
