### ISSUE TITLE
readme - p_excludeCols parameter not documented

### ISSUE THREAD

**Issue by v-hlotau** [mbleron/ExcelGen#52]
The documentation lacks the description of a parameter `p_excludeCols` in procedures `addSheetFromQuery`, `addSheetFromCursor` and `addTable`.
Was this intentional (maybe left only for testing purpose)?
I tried it today and found it pretty useful though.

**Comment by v-hlotau** [comment]
Thank you for clarification.

Will this (or some similar) parameter still be available after the formulas are implemented?

Use case:
the query which creates an Excel table has an additional column that contains a CSS-Style for highlighting specific rows (through `setTableRowProperties`).
This column have a standard name and shouldn't be displayed.

**Comment by mbleron** [comment]
Yes, the parameter will be there and documented.
For your use case, you'll also be able to use Excel's native conditional formatting (issue #2) which depends on formulas as well.

**Comment by mbleron** [comment]
Done in v4.1. See [addTable](https://github.com/mbleron/ExcelGen?tab=readme-ov-file#addtable-function).
