### ISSUE TITLE
style-showcase.sql error in procedure makeGradientSheet

### ISSUE THREAD

**Issue by GianTag** [mbleron/ExcelGen#53]
running the procedure, in proc makeGradientSheet, from the line:

ExcelGen.putCell(ctx, sheet6, 3, 1, p_style => ExcelGen.makeCellStyleCss(ctx, 'background: linear-gradient(89.2deg, rgb(0, 0, 0) 10.4%, rgb(255, 0, 0) 37.1%, rgb(255, 216, 51) 64.3%, rgb(255, 255, 255) 90.5%);'));

generate error :
19:20:22  ORA-06502: PL/SQL: errore : errore di conversione da carattere a numero di numero o valore

**Comment by mbleron** [comment]
Cannot reproduce on the latest ExcelGen version.
Please make sure you got all dependencies right.

**Comment by GianTag** [comment]
Hi, I found the problem!
To get around it, just set the decimal separator with a period or, in the ExcelTypes module, on line 1415, replace "token.nv := to_number(token.v);" with "token.nv := to_number(token.v,'999999.99');"

**Comment by mbleron** [comment]
Spot on! Thanks.
I have a little enhancement coming up on this component, I'll include the fix there at the same time.
