### ISSUE TITLE
Can ExcelGen hide a sheet?

### ISSUE THREAD

**Issue by FrFeCN** [mbleron/ExcelGen#54]
Sometimes it is necessary to add a sheet to excel to store basic data, but it is not necessary to display it. Can this feature be supported?

**Comment by mbleron** [comment]
Yes I can add that quite easily.
Should have done it a long time ago to be honest, but I felt there was no need for it until I introduce a way to actually access that hidden data, e.g. via defined names or formulas (upcoming features).

**Comment by FrFeCN** [comment]
Looking forward to your update and thank you for the powerful features of ExcelGen.

**Comment by mbleron** [comment]
Done in v4.0.
See for example [addSheet](https://github.com/mbleron/ExcelGen/blob/master/README.md#addsheet-function) function.
