### ISSUE TITLE
Excel Data Validation List on a column

### ISSUE THREAD

**Issue by FsFilipe** [mbleron/ExcelGen#58]
Is it possible to filter the available values of a column (Excel -> Data -> Data Validation -> Allow: List) based on a list of values in a hidden sheet (in the image attached the 'LOV' sheet is hidden)?

![image](https://github.com/mbleron/ExcelGen/assets/10554228/fc98e9be-55f9-4f52-8e8f-33340ea51204)
![image](https://github.com/mbleron/ExcelGen/assets/10554228/1f5aa73e-1a46-42e4-90f9-a76970f58437)
![image](https://github.com/mbleron/ExcelGen/assets/10554228/6c9007fc-da29-4308-ae1b-8fd4289cd581)

**Comment by FsFilipe** [comment]
That's amazing! Great work ;)

**Comment by mbleron** [comment]
Done in v4.2.

* [addDataValidationRule](https://github.com/mbleron/ExcelGen?tab=readme-ov-file#adddatavalidationrule-procedure)
* [setTableColumnValidationRule](https://github.com/mbleron/ExcelGen?tab=readme-ov-file#settablecolumnvalidationrule-procedure)
* [Data validation example](https://github.com/mbleron/ExcelGen?tab=readme-ov-file#data-validation)

**Comment by FsFilipe** [comment]
Thanks! ;)
