### ISSUE TITLE
Impossible to Create Link cell value

### ISSUE THREAD

**Issue by melDavila** [mbleron/ExcelGen#6]
Hi Marc Bleron!

I have not found how to set a special format for a particular column (or cell) to make the content link.

Is there a way to set the custom format? 
Similar to this:
![image](https://user-images.githubusercontent.com/14999833/131655534-42e90850-3401-4316-91cc-ca8c9d98a5f0.png)

**Comment by mbleron** [comment]
Hi Mel,

Right now, ExcelGen cannot create hyperlinks. Actually, it's a little more complicated than a simple cell format.
I'll consider your request as an enhancement for a future release.
Thanks for the idea.

**Comment by melDavila** [comment]
Thanks to consider as enhancement for a future release.
Best regards.

**Comment by mbleron** [comment]
Done in v4.1. 
Please see [addTableHyperlinkColumn](https://github.com/mbleron/ExcelGen?tab=readme-ov-file#addtablehyperlinkcolumn-procedure) and [putHyperlinkCell](https://github.com/mbleron/ExcelGen?tab=readme-ov-file#puthyperlinkcell-procedure).
