### ISSUE TITLE
Generating Excel that has a company logo on the top left border using Excelgen

### ISSUE THREAD

**Issue by NiltonMaganha** [mbleron/ExcelGen#60]
I'm trying to generate an Excel file that includes a company logo in the top left corner of the spreadsheet.

First I tried to use the command =IMAGE(  )

like: https://support.microsoft.com/en-us/office/image-function-7e112975-5e52-4f2a-b9da-1d913d51f5d5

but neither ExcelGen.putRichTextCell nor ExcelGen.putFormulaCell reconize the command.

Then, I converted the .png file to hex and tried to include in excel using :
ExcelGen.putCell(ctx, sheet, 2, 2, '<div style="margin-right: 59px; margin-bottom: 200px; height: 2px; width: 2px; box-shadow: #fff 0 0,#fff 0 1px,#fff ...........#fff 199px 58px"></div>');   but while trying to compile I receive the message that string is too large 

Finally I upload the image to an Oracle Table, and now I'm reading the CLOB, chunk the content and trying to execute several ExcelGen.putCell but even so it is not generating the image.

Can someone help me to execute this task of generate an Image (logo) inside an excel spreadsheet using Excelgen?

**Comment by mbleron** [comment]
I've added `IMAGE` to the list of supported functions, you should be able to use it provided : 
* you're on Office 365
* target image URL uses https protocol

The component is available from the ExcelCommons repository (I've not updated the submodule in ExcelGen yet) : [ExcelFmla.pkb](https://github.com/mbleron/ExcelCommons/blob/main/plsql/ExcelFmla.pkb)

Here's some sample code: 
```
declare
  ctx     ExcelGen.ctxHandle := ExcelGen.createContext(ExcelGen.FILE_XLSX);
  sheet1  ExcelGen.sheetHandle := ExcelGen.addSheet(ctx, 'sheet1');
begin
  ExcelGen.putStringCell(ctx, sheet1, 1, 1, 'https://cdn.countryflags.com/thumbs/france/flag-400.png');
  ExcelGen.putFormulaCell(ctx, sheet1, 2, 1, 'IMAGE(A1)');
  ExcelGen.createFile(ctx, 'TEST_DIR', 'test-image.xlsx');
  ExcelGen.closeContext(ctx); 
end;
/
```

NB: image retrieval in Excel might be blocked initially for security reasons, adjust the settings accordingly.

Let me know if it works for you.

**Comment by NiltonMaganha** [comment]
Thank you very much, your new routine worked perfectly.

Now I'm able to insert Company Logo in the excel files.

Thank you very much !!
