### ISSUE TITLE
Formula select individual cells

### ISSUE THREAD

**Issue by BorjaRRR** [mbleron/ExcelGen#65]
Hello,

Can't use semicolon in formulas: SUM(A1;B3)

ORA-20000: [line 1, col 8] Unexpected token: ;

**Comment by mbleron** [comment]
Hi,

It's explained in the README : [Formula Support](https://github.com/mbleron/ExcelGen?tab=readme-ov-file#formula-support)

> Formulas must be entered in English locale, specifically:
> 
> * Decimal separator = . (dot)
> * **Argument separator, union operator, array row-item separator = , (comma)**
> * Array row separator = ; (semicolon)

**Comment by BorjaRRR** [comment]
Ups sorry you're rigth.

Thanks Marc!
