### ISSUE TITLE
Free initial lines to insert a description.

### ISSUE THREAD

**Issue by melDavila** [mbleron/ExcelGen#8]
Currently the generated table is inserted fix position A1.
It would be very interesting to be able to place the table in the desired position, leaving space at the top.

And a method to assign the text to those cells.

**Comment by mbleron** [comment]
Implemented in v3.0.
See Table and Cell management [procedures](https://github.com/mbleron/ExcelGen#excelgen-subprograms-and-usage), and this [example](https://github.com/mbleron/ExcelGen#master-details).
