### ISSUE TITLE
Impossible to set 'Wrap text' Format for TEXT cells

### ISSUE THREAD

**Issue by melDavila** [mbleron/ExcelGen#9]
Hi again.
We have some description cells, with a very large description,  that need to set as 'Wrap text'.
We have options for DATE an NUMBERS but not for text.

function makeCellStyle (
  p_ctxId       in ctxHandle
, p_numFmtCode  in varchar2 default null
, p_font        in CT_Font default null
, p_fill        in CT_Fill default null
, p_border      in CT_Border default null
, p_alignment   in CT_CellAlignment default null
**, p_wrap_text      in boolean default false**
)

**or in**

function makeAlignment (
  p_horizontal  in varchar2 default null
, p_vertical    in varchar2 default null
**, p_wrap_text      in boolean default null**
)

![image](https://user-images.githubusercontent.com/14999833/131883222-4cab2644-a7d3-4dfd-b58e-fd819b0ad1bf.png)

I think this is to put in **Pull request** but :
"There aren’t any open pull requests."
![image](https://user-images.githubusercontent.com/14999833/131883795-a7535a91-12fa-4d82-96a4-9a1f8bdd3a8c.png)

**Comment by mbleron** [comment]
Fixed in v2.3
